### ISSUE TITLE
Erro, focus

### ISSUE THREAD

**Issue by Apocryphoon** [miguelrisquelme/bot-whatsapp#1]
Boa noite grande, fui tentar rodar por curiosidade, estou testando com minha namorada e ele me deu erro nos 2 campos aonde ele deveria pegar a classe da campo, tive que modificar para que ele possa rodar, n sei se usei certo pois ele retorna o seguinte erro:

https://prnt.sc/vn58bt

edit: Consegui solucionar

**Comment by rniguel** [comment]
Boa noite mano, desculpa a demora, então esse erro ai é que a classe tá
errada, se quiser eu ajudo em call pode ficar até mais fácil, porque se pá
essa classe ela muda de navegador para navegador.

Mas eu acho que vendo ali eu descobri, tenta coloca assim:

await page.waitForSelector("div._1hRBM");

Eu simplesmente add div na frente do ponto

meu discord ae: miguelrisquelme#2004
meu server:  https://discord.gg/6rbD5aJ

Tmj e valeu pelo contato!

**Comment by Apocryphoon** [comment]
Bom dia, então quando eu lê o erro não se mostrou claro, já que era um erro no try cath, porém eu já havia mudado as 2 div a de busca e a de seleção, eu vi sua observação no código, mudei e voltou a funcionar, obrigado!

**Comment by rniguel** [comment]
Opa que bom que voltou a funcionar, tmj manin
